### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by olivergondza**

### CODE REVIEW

**Comment by gabemontero** [comment]
Hi @olivergondza - could you elaborate a bit on the purpose here?  Perhaps related to the ci-cd flows in the jenkinsci infrastructure?

**Comment by olivergondza** [comment]
Exactly, this is to enable the standard CI builds for commits/PRs at https://ci.jenkins.io/job/Plugins/.

**Comment by gabemontero** [comment]
OK thanks for the confirmation.  It should be benign for the ci/cd flow on our end.  Let's see what happens.

@bparees fyi

**Comment by olivergondza** [comment]
Thanks, you can see it running here: https://ci.jenkins.io/job/Plugins/job/openshift-login-plugin/

**Pull request merged**
